### ISSUE TITLE
Returns first occurrence for duplicates

### ISSUE THREAD

**Issue by lmonilsson** [AAudusseau/webconfig-parser#1]
`ConfigurationManager.AppSettings["key"]` in .NET returns the last occurrence if there are multiple entries for "key". Is there a reason why this library returns the first occurrence? Returning the last occurrence would give the same behavior as .NET reading Web.config.

**Comment by lmonilsson** [comment]
Thanks!

**Comment by lmonilsson** [comment]
It would help if 0.2.0 were released on npm. The last version there is still 0.1.0. I'm guessing that it's an oversight. Thanks.

**Comment by AAudusseau** [comment]
Yes sorry for the delay ! It's done.
